-- EDA--

--- Database Exploration --- 

-- Explore all objects in the database:
select * from INFORMATION_SCHEMA.TABLES;

-- Explore all the columns in the database:
select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'dim_customers';

--- Dimensions Exploration --- 
-- Explore the country col 
select distinct country from gold.dim_customers

-- explore all categories 'the major divisions'
select distinct category,subcategory,product_name 
from gold.dim_products
order by 1,2,3;

--- Date Exploration --- 
-- find the date of the first and last order;
-- how many years of sales are available 
select min(order_date) as first_order_date,
max(order_date) as last_order_date,
datediff(year, min(order_date), max(order_date)) as order_range_year
from gold.fact_sales;

-- find the youngest and oldest customer:
select min(birthdate) as youngest_customer,
datediff(year, min(birthdate), GETDATE()) as oldest_age,
max(birthdate) as oldest_customer,
datediff(year, max(birthdate), GETDATE()) as youngest_age
from gold.dim_customers.

--- Measure explorations----
-- find the total sales:

select sum(sales_amount) as total_sales 
from gold.fact_sales; -- 29M

-- find how many items are sold:
select sum(quantity) as total_quantity 
from gold.fact_sales; -- 60K

-- find the average selling price:
select avg(price) as total_quantity 
from gold.fact_sales; --486

-- find the total number of orders:
select count(order_number) as total_orders 
from gold.fact_sales;
select count(distinct order_number) as unique_orders 
from gold.fact_sales; -- 27K

-- Find the total number of products
select count(product_key) as total_products 
from gold.dim_products;
select count(distinct product_key) as unique_products 
from gold.dim_products;

-- Find the total number of customers:
select count(customer_key) as total_customer
from gold.dim_customers;

-- Find the total nuber of customer that has placed an order:
select count(distinct customer_key) as total_customer
from gold.fact_sales;

-- Generate a report that shows all the key metrics of the business:
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Products', COUNT(DISTINCT product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total Customers', COUNT(customer_key) FROM gold.dim_customers;

-- Magnitude Analysis--
-- find the total customers by countries:
select country, count(customer_key) as total_customer 
from gold.dim_customers
group by country
order by total_customer desc;

-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;

-- Ranking Ananlysis -- 
-- Which 5 Products generate the higest revenue?
select TOP 5
p.product_name, sum(f.sales_amount) as total_revenue
from gold.fact_sales as f
left join gold.dim_products as p
on f.product_key = p.product_key
group by p.product_name
order by total_revenue desc;
-- Using window functions:
select * from (
select 
p.product_name, 
sum(f.sales_amount) as total_revenue,
ROW_NUMBER() over(order by sum(f.sales_amount) desc) as rank_products
from gold.fact_sales as f
left join gold.dim_products as p
on f.product_key = p.product_key
group by p.product_name) as t
where rank_products <= 5;

-- what are the 5 Worst-performing products in terms of sales?
select TOP 5
p.product_name, sum(f.sales_amount) as total_revenue
from gold.fact_sales as f
left join gold.dim_products as p
on f.product_key = p.product_key
group by p.product_name
order by total_revenue asc;

-- Find the top 10 customers who have generated the highest revenue
SELECT TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- The 3 customers with the fewest orders placed
SELECT TOP 3
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_orders ;